### ISSUE TITLE
better error handling in devices.rs

### ISSUE THREAD

**Issue by DonatJR** [DonatJR/adbackup#8]
use `failure` for error handling in [devices.rs](https://github.com/DonatJR/adbackup/blob/develop/src/devices.rs) as indicated by the FIXME's in the code

we could do this together for the first time if you want to, so we can both get acquainted with the `failure`-module

**Comment by SailReal** [comment]
learn-duel took too much time last week so there was no time left to dive into this issue together. 

Just mentioned #4 in the commit but it is also relevant for this issue here: https://github.com/DonatJR/adbackup/commit/c30191a6fe4b9be9eeda1131476c6497877d665e
What do you think about that strategy?

**Comment by DonatJR** [comment]
looks good to me and you are more familiar with the `error_chain` concepts, so 👍
